### ISSUE TITLE
Should have launch file

### ISSUE THREAD

**Issue by jim-v** [UbiquityRobotics/Robot_Commander#1]
There should be a ROS launch file.  If SSL is used, arguments should be passed to rosbridge_websocket.launch, instead of modifying it.

**Comment by jrlandau** [comment]
It would be nice if rosbridge would accept either ssl or non-ssl.  Reason:
We must use SSL from a browser, but don't need it from a phone.  Do you
know if this is possible?

**Comment by jim-v** [comment]
I think you would need to run two rosbridge servers on different ports, one
with SSL and one without.

**Comment by jrlandau** [comment]
That sounds like a good idea to me.  I'm thinking in terms of the image
that we ship. Would there be any problems with doing that?

**Comment by jrlandau** [comment]
I am not sure what should or could be in a launch file for RC.  Everything it uses is in the robot and should be running at bootup.  RC itself does not get launched.

**Comment by jim-v** [comment]
Yes, the issue was intended to make sure that the nodes that are needed are
launched.  Let's keep it open until we have verified it is.

**Comment by rohbotics** [comment]
Magni robot does this currently, so I am considering this resolved
