### ISSUE TITLE
Speech Commands Broken

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/Robot_Commander#7]
Moto X 2014 Android Lollipop

![media-20171222](https://user-images.githubusercontent.com/2825327/34310007-d17da59a-e709-11e7-8c73-167897626ab7.png)

Seems like there is a problem with the speech api returning multiple possible detected speeches.

**Comment by jrlandau** [comment]
I think the problem is that the program does not support any of those
distance specifications.  When allowing alternatives, it's hard to know
where to stop.
